### ISSUE TITLE
How does it work

### ISSUE THREAD

**Issue by DonMart** [spidgorny/energy-monitor#3]
![foto_16Feb_21_13](https://user-images.githubusercontent.com/61888552/77064942-b0525d00-69e0-11ea-9986-aa5c0c7a1449.jpg)
Hi there, I love your project.
I've managed to copy your project on my raspberry pi.
I've created a folder ' cache' and put a few photo of my energymeter.

And when I run ' python3 index.py'
I get the following error:

pi@raspberrypi:~/energie/python $ python3 index.py
Reading files...
file ../cache/foto_01Mar_20_24.jpg
detectSkew: %.1f deg -9.529628230229278
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    x.next_image()
  File "/home/pi/energie/python/Recognize/Canny.py", line 38, in next_image
    self.render()
  File "/home/pi/energie/python/Recognize/Canny.py", line 42, in render
    straight, edges, contimage, isolated, digits = p.process()
  File "/home/pi/energie/python/Image/Pipeline.py", line 28, in process
    contimage = self.cannify.process()
  File "/home/pi/energie/python/Image/Cannify.py", line 19, in process
    contimage, contours, hierarchy = cv2.findContours(self.img, mode=cv2.RETR_TREE, method=cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

Can you please help me, what happens? What went wrong?
I am new to github, maybe I can show you how my photos look like.

Hping to hear from you.
Thanks in advance,
Greetings Mart

**Comment by spidgorny** [comment]
Please upload the photo here as a comment. I'll try to reproduce the issue and see if the code can be improved.

**Comment by DonMart** [comment]
![foto_16Mar_22_30](https://user-images.githubusercontent.com/61888552/77075305-670b0900-69f2-11ea-8a0f-cd1786394c7d.jpg)
this is an example of one of my pictures

**Comment by spidgorny** [comment]
I've fixed this particular issue that you reported. I've also moved some of the hard-coded values to the config file.
So now it will go further down the process, but will fail later because your image contains two lines of digits. The system tries to find the center-line of all digits, but will fail as there are two lines of digits.
It will also output multiple images after each step, so you can check where it's stuck and tweak the config file.
Let me know if it works any better now.
If I find the time I'll crop your image and try to detect numbers in it.

**Comment by DonMart** [comment]
Hi Spidgorny,
thanks for your reply.
I've managed to write a script, which crops one picture into 2 images with only the digits. So now I have an image with only one line of digits.
![foto_16Mar_22_30_1](https://user-images.githubusercontent.com/61888552/77420499-701d2100-6dca-11ea-8a56-3db8ca36f1ce.jpg)
![foto_16Mar_22_30_2](https://user-images.githubusercontent.com/61888552/77420501-70b5b780-6dca-11ea-8e35-706e90515f13.jpg)

* How many files does the sustem need for index/training?
- First I got an error: could not find ' training directory' 
I made 'python/training'  and the error is gone.

* At this time I only got 4 pictures,and not alle the different 0-9 digits.

* The current stage is:
----------------------------------
pi@raspberrypi:~/energie/python $ python3 index.py
Reading files...
file ../cache/foto_01Mar_20_24_1.jpg
sample_size <class 'tuple'> (30, 15)
debug True
HoughLines...
cThreshold 140
2 lines
detectSkew: %.1f deg 0.49999967247978816
len contours 210
len contours2 8
average aspect 0.5673555546742363
len contours3 7
average_y 106
average_height 58.07142857142857
len contours4 7
small 131
unique 138 97
len digits 5
self.multiprocessing False
original shape 5 (117, 68, 3)
resulting shape 5 (450,)
len samples 5 (450,)
to_delete 0
removeInf (0, 450) (0,)
removeInf (0, 450) (0,)
Traceback (most recent call last):
  File "index.py", line 9, in <module>
    x.next_image()
  File "/home/pi/energie/python/Recognize/Canny.py", line 51, in next_image
    self.render()
  File "/home/pi/energie/python/Recognize/Canny.py", line 86, in render
    recognize = self.recognize(samples)
  File "/home/pi/energie/python/Recognize/Canny.py", line 103, in recognize
    clf.fit(all_digits, all_numbers)
  File "/home/pi/.local/lib/python3.7/site-packages/sklearn/neighbors/_base.py", line 1126, in fit
    X, y = check_X_y(X, y, "csr", multi_output=True)
  File "/home/pi/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 755, in check_X_y
    estimator=estimator)
  File "/home/pi/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 586, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 450)) while a minimum of 1 is required.
--------------

I hope you have some time to help me to get any further.
Thanks in advance,
greets.

**Comment by DonMart** [comment]
Hi there,
could you please have a look at my problem? I have no clue how to continue. What could be my next step
thanks in advance
stafe save,
Mart
